// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHMOdazZPIbGyGuyuyWh3eueIXAWd22JI',
    appId: '1:673466007097:web:36710f9ba6317c77ab97e8',
    messagingSenderId: '673466007097',
    projectId: 'video-uploader-696fa',
    authDomain: 'video-uploader-696fa.firebaseapp.com',
    storageBucket: 'video-uploader-696fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVP-33Ms-_fPgUYNdXN5DYop_79syGw_c',
    appId: '1:673466007097:android:b9efd400a1b57d53ab97e8',
    messagingSenderId: '673466007097',
    projectId: 'video-uploader-696fa',
    storageBucket: 'video-uploader-696fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBde-EWalrupkbyzG5uebqK_mgalXqPx78',
    appId: '1:673466007097:ios:1468420e38d2f2d3ab97e8',
    messagingSenderId: '673466007097',
    projectId: 'video-uploader-696fa',
    storageBucket: 'video-uploader-696fa.appspot.com',
    iosBundleId: 'com.example.videoUploader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBde-EWalrupkbyzG5uebqK_mgalXqPx78',
    appId: '1:673466007097:ios:1468420e38d2f2d3ab97e8',
    messagingSenderId: '673466007097',
    projectId: 'video-uploader-696fa',
    storageBucket: 'video-uploader-696fa.appspot.com',
    iosBundleId: 'com.example.videoUploader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHMOdazZPIbGyGuyuyWh3eueIXAWd22JI',
    appId: '1:673466007097:web:de3c4e09538de181ab97e8',
    messagingSenderId: '673466007097',
    projectId: 'video-uploader-696fa',
    authDomain: 'video-uploader-696fa.firebaseapp.com',
    storageBucket: 'video-uploader-696fa.appspot.com',
  );
}
